Add CI check confirming build is up to date with source (#9)

diff --git a/.github/workflows/feature-branch-ci.yml b/.github/workflows/feature-branch-ci.yml
--- a/.github/workflows/feature-branch-ci.yml
+++ b/.github/workflows/feature-branch-ci.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
   
-  test-src:
+  feature-branch-ci:
     # test the code in src/
     runs-on: ubuntu-latest
     steps: 
@@ -24,6 +24,25 @@ jobs:
       run: yarn test
     - name: Lint check source code
       run: yarn lint
-
-
-
+    - name: Confirm build is up-to-date
+      run: |
+        build_sum=$(sha1sum dist/uncertaintext.js | awk '{ print $1 }')
+        yarn build  # updates dist/uncertaintext.js
+        rebuild_sum=$(sha1sum dist/uncertaintext.js | awk '{ print $1 }')
+        if [ "$rebuild_sum" = "$build_sum" ]; then
+          echo "Build is up to date, cool."
+        else
+          echo "Build is NOT up to date, fail!"
+          exit 1
+        fi
+    - name: Confirm example page is up-to-date
+      run: |
+        build_sum=$(sha1sum dist/uncertaintext.js | awk '{ print $1 }')
+        example_sum=$(sha1sum docs/uncertaintext.js | awk '{ print $1 }')
+        if [ "$example_sum" = "$build_sum" ]; then
+          echo "Example is up to date, cool."
+        else
+          echo "Example is NOT up to date, fail!"
+          exit 1
+        fi
+        
